=== intelie/esper/esperio-db/etc/esperio-db-configuration-4-0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.espertech.com/schema/esperio-db" elementFormDefault="qualified" xmlns:esperio="http://www.espertech.com/schema/esperio-db" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="esperio-db-configuration">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded" minOccurs="0">
				<xs:choice>
					<xs:element ref="esperio:jdbc-connection" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element ref="esperio:dml" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element ref="esperio:upsert" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element ref="esperio:executors" minOccurs="0" maxOccurs="unbounded"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="jdbc-connection">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded" minOccurs="0">
				<xs:choice>
					<xs:element ref="esperio:datasource-connection" minOccurs="0"/>
					<xs:element ref="esperio:datasourcefactory-connection" minOccurs="0"/>
					<xs:element ref="esperio:drivermanager-connection" minOccurs="0"/>
					<xs:element ref="esperio:connection-settings" minOccurs="0"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="executors">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="esperio:executor" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="executor">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="threads" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="config-param">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="datasource-connection">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="esperio:env-property" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="context-lookup-name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="datasourcefactory-connection">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="esperio:env-property" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class-name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="connection-properties">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="esperio:env-property" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="connection-cache-properties">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="esperio:env-property" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="env-property">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="drivermanager-connection">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="esperio:connection-arg" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class-name" type="xs:string" use="required"/>
			<xs:attribute name="url" type="xs:string" use="required"/>
			<xs:attribute name="user" type="xs:string" use="optional"/>
			<xs:attribute name="password" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="connection-settings">
		<xs:complexType>
			<xs:attribute name="auto-commit" type="xs:boolean" use="optional"/>
			<xs:attribute name="catalog" type="xs:string" use="optional"/>
			<xs:attribute name="read-only" type="xs:boolean" use="optional"/>
			<xs:attribute name="transaction-isolation" type="xs:int" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="connection-arg">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="config-xml">
		<xs:complexType>
			<xs:sequence>
				<xs:any minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="dml">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded" minOccurs="0">
				<xs:choice>
					<xs:element name="sql" type="xs:string" minOccurs="1" maxOccurs="1"/>
					<xs:element ref="esperio:bindings" minOccurs="0" maxOccurs="unbounded"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="connection" type="xs:string" use="optional"/>
			<xs:attribute name="stream" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="optional"/>
			<xs:attribute name="executor-name" type="xs:string" use="optional"/>
			<xs:attribute name="retry" type="xs:int" use="optional"/>
			<xs:attribute name="retry-interval-sec" type="xs:double" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="upsert">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded" minOccurs="0">
				<xs:choice>
					<xs:element ref="esperio:keys" minOccurs="1" maxOccurs="unbounded"/>
					<xs:element ref="esperio:values" minOccurs="1" maxOccurs="unbounded"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="connection" type="xs:string" use="optional"/>
			<xs:attribute name="stream" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="optional"/>
			<xs:attribute name="table-name" type="xs:string" use="required"/>
			<xs:attribute name="executor-name" type="xs:string" use="optional"/>
			<xs:attribute name="retry" type="xs:int" use="optional"/>
			<xs:attribute name="retry-interval-sec" type="xs:double" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="sql">
		<xs:complexType>
			<xs:sequence>			
				<xs:element name="query" type="xs:string" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="bindings">
		<xs:complexType>
			<xs:sequence>			
				<xs:element ref="esperio:parameter" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="initial-value">
		<xs:complexType>
			<xs:sequence>			
				<xs:element ref="esperio:value" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="keys">
		<xs:complexType>
			<xs:sequence>			
				<xs:element ref="esperio:column" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="values">
		<xs:complexType>
			<xs:sequence>			
				<xs:element ref="esperio:column" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="value">
		<xs:complexType>
			<xs:attribute name="pos" type="xs:int" use="required"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
			<xs:attribute name="type" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="parameter">
		<xs:complexType>
			<xs:attribute name="pos" type="xs:int" use="required"/>
			<xs:attribute name="property" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="column">
		<xs:complexType>
			<xs:attribute name="property" type="xs:string" use="required"/>
			<xs:attribute name="column" type="xs:string" use="required"/>
			<xs:attribute name="type" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== intelie/esper/esperio-db/etc/esperio-db-sample-config.xml
<?xml version="1.0" encoding="UTF-8"?><!-- 	Sample esperio-db configuration file.--><esperio-db-configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.espertech.com/schema/esperio-db" xsi:noNamespaceSchemaLocation="esperio-db-configuration-4-0.xsd">	<!--		Sample for a connection obtained from a DataSource looking via JNDI.     -->	<jdbc-connection name="db1">		<datasource-connection context-lookup-name="java:comp/env/jdbc/mydb">			<env-property name="java.naming.factory.initial" value="com.myclass.CtxFactory"/>			<env-property name="java.naming.provider.url" value="iiop://localhost:1050"/>		</datasource-connection>	</jdbc-connection>	<!--		Sample for a connection obtained from a BasicDataSourceFactory implementation.		This example also explicitly sets the pooled attribute and sets the catalog, auto-commit, read-only and isolation level.     -->	<jdbc-connection name="db2">		<datasourcefactory-connection class-name="org.apache.commons.dbcp.BasicDataSourceFactory">	<!-- For a complete list of properties see Apache DBCP. -->			<env-property name="username" value ="myusername"/>			<env-property name="password" value ="mypassword"/>			<env-property name="driverClassName" value ="com.mysql.jdbc.Driver"/>			<env-property name="url" value ="jdbc:mysql://localhost/test"/>			<env-property name="initialSize" value ="2"/>		</datasourcefactory-connection>		<connection-settings auto-commit="true" catalog="TEST" read-only="true" transaction-isolation="0"/>	</jdbc-connection>	<!--		Sample for a connection obtained from DriverManager.     -->	<jdbc-connection name="db3">		<drivermanager-connection class-name="my.sql.Driver" url="jdbc:mysql://localhost/test?user=root&amp;password=welcome" user="myuser" password="mypassword">			<connection-arg name="user" value ="myuser"/>			<connection-arg name="password" value ="mypassword"/>			<connection-arg name="somearg" value ="someargvalue"/>		</drivermanager-connection>	</jdbc-connection>	<!--      Sample for a DML statement which inserts new rows.       A work queue name must be defined to point to a threading configuration.	-->	<dml connection="db1" stream="InsertToDBStream" name="MyInsertQuery" executor-name="queue1" retry="2" retry-interval-sec="1">		<sql>insert into MyEventStore(key1, value1, value2)values (?, ?, ?)</sql>		<bindings>			<parameter pos="1" property="eventProperty1"/>			<parameter pos="2" property="eventProperty2"/>			<parameter pos="3" property="eventProperty3"/>		</bindings>	</dml>	<!--      Sample for an UPSERT: an Update, followed by an Insert if the row count of the update was zero.    -->    <upsert connection="db1" stream="UpdateInsertDBTableTrigger" name="UpdateInsertSample" table-name="MyKeyedTable" executor-name="queue1" retry="3">		<keys>			<column property="eventProperty1" column="keyColumn1" type="varchar"/>			<column property="eventProperty2" column="keyColumn2" type="varchar"/>		</keys>		<values>			<column property="eventProperty3" column="valueColumn1" type="varchar"/>			<column property="eventProperty4" column="valueColumn2" type="integer"/>		</values>    </upsert>    	<!--      Sample for a work queue with 2 threads.    -->    <executors>		<executor name="queue1" threads="2"/>    </executors></esperio-db-configuration>
