=== intelie/esper/trunk/esper/etc/esper-configuration-1-0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="esper-configuration">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="event-type-auto-alias" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="event-type" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="auto-import" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="database-reference" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="plugin-view" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="plugin-aggregation-function" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="plugin-pattern-guard" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="plugin-pattern-observer" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="adapter-loader" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="engine-settings" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="event-type-auto-alias">
		<xs:complexType>
			<xs:attribute name="package-name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="event-type">
		<xs:complexType>
			<xs:choice>
				<xs:sequence>
					<xs:element ref="xml-dom" minOccurs="0"/>
					<xs:element ref="java-util-map" minOccurs="0"/>
					<xs:element ref="legacy-type" minOccurs="0"/>
				</xs:sequence>
			</xs:choice>
			<xs:attribute name="alias" type="xs:string" use="required"/>
			<xs:attribute name="class" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="xml-dom">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="namespace-prefix" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="xpath-property" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="root-element-name" type="xs:string" use="required"/>
			<xs:attribute name="root-element-namespace" type="xs:string" use="optional"/>
			<xs:attribute name="default-namespace" type="xs:string" use="optional"/>
			<xs:attribute name="schema-resource" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="namespace-prefix">
		<xs:complexType>
			<xs:attribute name="prefix" type="xs:string" use="required"/>
			<xs:attribute name="namespace" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="xpath-property">
		<xs:complexType>
			<xs:attribute name="property-name" type="xs:string" use="required"/>
			<xs:attribute name="xpath" type="xs:string" use="required"/>
			<xs:attribute name="type" type="xpath-type" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="xpath-type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="number"/>
			<xs:enumeration value="string"/>
			<xs:enumeration value="boolean"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="java-util-map">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="map-property"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="map-property">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="class" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="auto-import">
		<xs:complexType>
			<xs:attribute name="import-name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="legacy-type">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="method-property" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="field-property" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="accessor-style" type="accessorStyleEnum" use="optional"/>
			<xs:attribute name="code-generation" type="codeGenerationEnum" use="optional"/>
			<xs:attribute name="property-resolution-style" type="propertyResolutionStyleEnum" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="method-property">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="accessor-method" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="field-property">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="accessor-field" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="accessorStyleEnum">
		<xs:restriction base="xs:token">
			<xs:enumeration value="javabean"/>
			<xs:enumeration value="explicit"/>
			<xs:enumeration value="public"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="codeGenerationEnum">
		<xs:restriction base="xs:token">
			<xs:enumeration value="enabled"/>
			<xs:enumeration value="disabled"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="propertyResolutionStyleEnum">
		<xs:restriction base="xs:token">
			<xs:enumeration value="case_sensitive"/>
			<xs:enumeration value="case_insensitive"/>
			<xs:enumeration value="distinct_case_insensitive"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="database-reference">
		<xs:complexType>
			<xs:choice>
				<xs:sequence>
					<xs:element ref="datasource-connection" minOccurs="0"/>
					<xs:element ref="drivermanager-connection" minOccurs="0"/>
					<xs:element ref="connection-settings" minOccurs="0"/>
					<xs:element ref="connection-lifecycle" minOccurs="0"/>
					<xs:element ref="lru-cache" minOccurs="0"/>
					<xs:element ref="expiry-time-cache" minOccurs="0"/>
				</xs:sequence>
			</xs:choice>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="datasource-connection">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="env-property" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="context-lookup-name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="env-property">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="drivermanager-connection">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="connection-arg" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class-name" type="xs:string" use="required"/>
			<xs:attribute name="url" type="xs:string" use="required"/>
			<xs:attribute name="user" type="xs:string" use="optional"/>
			<xs:attribute name="password" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="connection-arg">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="connection-settings">
		<xs:complexType>
			<xs:attribute name="auto-commit" type="xs:boolean" use="optional"/>
			<xs:attribute name="catalog" type="xs:string" use="optional"/>
			<xs:attribute name="read-only" type="xs:boolean" use="optional"/>
			<xs:attribute name="transaction-isolation" type="xs:int" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="connection-lifecycle">
		<xs:complexType>
			<xs:attribute name="value" type="connection-lifecycle-enum" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="connection-lifecycle-enum">
		<xs:restriction base="xs:token">
			<xs:enumeration value="pooled"/>
			<xs:enumeration value="retain"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="lru-cache">
		<xs:complexType>
			<xs:attribute name="size" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="expiry-time-cache">
		<xs:complexType>
			<xs:attribute name="max-age-seconds" type="xs:double" use="required"/>
			<xs:attribute name="purge-interval-seconds" type="xs:double" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="plugin-view">
		<xs:complexType>
			<xs:attribute name="namespace" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="factory-class" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="plugin-aggregation-function">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="function-class" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="plugin-pattern-guard">
		<xs:complexType>
			<xs:attribute name="namespace" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="factory-class" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="plugin-pattern-observer">
		<xs:complexType>
			<xs:attribute name="namespace" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="factory-class" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="adapter-loader">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="init-arg" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="class-name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="init-arg">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="engine-settings">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="defaults" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="defaults">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="threading" minOccurs="0"/>
				<xs:element ref="event-meta" minOccurs="0"/>
				<xs:element ref="view-resources" minOccurs="0"/>
				<xs:element ref="logging" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="threading">
		<xs:complexType>
			<xs:choice>
				<xs:sequence>
					<xs:element ref="listener-dispatch" minOccurs="0"/>
					<xs:element ref="insert-into-dispatch" minOccurs="0"/>
					<xs:element ref="internal-timer" minOccurs="0"/>
				</xs:sequence>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="event-meta">
		<xs:complexType>
			<xs:choice>
				<xs:sequence>
					<xs:element ref="class-property-resolution" minOccurs="0"/>
				</xs:sequence>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="listener-dispatch">
		<xs:complexType>
			<xs:attribute name="preserve-order" type="xs:boolean" use="required"/>
			<xs:attribute name="timeout-msec" type="xs:long" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="insert-into-dispatch">
		<xs:complexType>
			<xs:attribute name="preserve-order" type="xs:boolean" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="internal-timer">
		<xs:complexType>
			<xs:attribute name="enabled" type="xs:boolean" use="required"/>
			<xs:attribute name="msec-resolution" type="xs:long" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="class-property-resolution">
		<xs:complexType>
			<xs:attribute name="style" type="propertyResolutionStyleEnum" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="view-resources">
		<xs:complexType>
			<xs:choice>
				<xs:sequence>
					<xs:element ref="share-views" minOccurs="0"/>
				</xs:sequence>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="share-views">
		<xs:complexType>
			<xs:attribute name="enabled" type="xs:boolean" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="logging">
		<xs:complexType>
			<xs:choice>
				<xs:sequence>
					<xs:element ref="execution-path" minOccurs="0"/>
				</xs:sequence>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="execution-path">
		<xs:complexType>
			<xs:attribute name="enabled" type="xs:boolean" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== intelie/esper/trunk/esper/etc/regression/esper.test.readconfig.cfg.xml
<?xml version="1.0" encoding="UTF-8"?><esper-configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../esper-configuration-1-0.xsd">		<event-type alias="MySampleEventOne" class="com.mycompany.myapp.MySampleEventOne"/>	<event-type alias="MySampleEventTwo" class="com.mycompany.myapp.MySampleEventTwo"/>	<event-type alias="MyNoSchemaXMLEventAlias">		<xml-dom root-element-name="MyNoSchemaEvent" >			<xpath-property property-name="element1" xpath="/myevent/element1" type="number"/>		</xml-dom>	</event-type>		<event-type alias="MySchemaXMLEventAlias">		<xml-dom root-element-name="MySchemaEvent" root-element-namespace="samples:schemas:simpleSchema" schema-resource="MySchemaXMLEvent.xsd" 				default-namespace="default-name-space">			<namespace-prefix prefix="ss" namespace="samples:schemas:simpleSchema"/>			<xpath-property property-name="element1" xpath="/myevent/element1" type="number"/>		</xml-dom>	</event-type>		<event-type alias="MyMapEvent">		<java-util-map>		  	<map-property name="myInt" class="int"/>	  		<map-property name="myString" class="string"/>	  	</java-util-map>	</event-type>		<event-type alias="MyLegacyTypeEvent" class="com.mycompany.package.MyLegacyTypeEvent">		<legacy-type accessor-style="public" code-generation="enabled">			<method-property name="mymethodprop" accessor-method="myAccessorMethod" />			<field-property name="myfieldprop" accessor-field="myFieldName" />		</legacy-type>	</event-type>	<auto-import import-name="com.mycompany.myapp.*"/>	<auto-import import-name="com.mycompany.myapp.ClassOne"/>		<database-reference name="mydb1">		<datasource-connection context-lookup-name="java:comp/env/jdbc/mydb">			<env-property name="java.naming.factory.initial" value ="com.myclass.CtxFactory"/>			<env-property name="java.naming.provider.url" value ="iiop://localhost:1050"/>		</datasource-connection>		<connection-lifecycle value="pooled"/>		<lru-cache size="10"/>	</database-reference>		<database-reference name="mydb2">		<drivermanager-connection class-name="my.sql.Driver" url="jdbc:mysql://localhost" user="myuser1" password="mypassword1">			<connection-arg name="user" value ="myuser2"/>			<connection-arg name="password" value ="mypassword2"/>			<connection-arg name="somearg" value ="someargvalue"/>		</drivermanager-connection>		<connection-settings auto-commit="false" catalog="test" read-only="true" transaction-isolation="3" />			<connection-lifecycle value="retain"/>		<expiry-time-cache max-age-seconds="60.5" purge-interval-seconds="120.1"/>	</database-reference>	<plugin-view namespace="ext0" name="myview0" factory-class="com.mycompany.MyViewFactory0" />	<plugin-view namespace="ext1" name="myview1" factory-class="com.mycompany.MyViewFactory1" />	<adapter-loader name="Loader1" class-name="net.esper.support.adapter.SupportLoaderOne">		<init-arg name="name1" value="val1"/>		<init-arg name="name2" value="val2"/>	</adapter-loader>	<adapter-loader name="Loader2" class-name="net.esper.support.adapter.SupportLoaderTwo" /></esper-configuration>

=== intelie/esper/trunk/esperio/etc/esper.yves.test.readconfig.cfg.xml
<?xml version="1.0" encoding="UTF-8"?><esper-configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../esper-configuration-1-0.xsd">		<event-type alias="MySampleEventOne" class="net.esper.example.stockticker.eventbean.StockTick"/>	<event-type alias="MySampleEventTwo" class="net.esper.example.stockticker.eventbean.StockTick"/>	<event-type alias="MyNoSchemaXMLEventAlias">		<xml-dom root-element-name="MyNoSchemaEvent" >			<xpath-property property-name="element1" xpath="/myevent/element1" type="number"/>		</xml-dom>	</event-type>		<event-type alias="MySchemaXMLEventAlias">		<xml-dom root-element-name="MySchemaEvent" root-element-namespace="samples:schemas:simpleSchema" xsi:schemaLocation="samples:schemas:simpleSchema simpleSchema.xsd" 				default-namespace="default-name-space">				<namespace-prefix prefix="ss" namespace="samples:schemas:simpleSchema"/>			<xpath-property property-name="element1" xpath="/myevent/element1" type="number"/>		</xml-dom>	</event-type>		<event-type alias="MyMapEvent">		<java-util-map>		  	<map-property name="myInt" class="java.lang.Integer"/>		  	<map-property name="myDouble" class="java.lang.Double"/>	  		<map-property name="myString" class="java.lang.String"/>		  	<!-- map-property name="myInt" class="int"/>	  		<map-property name="myString" class="string"/ -->	  			  	</java-util-map>	</event-type>	<!-- auto-import import-name="com.mycompany.myapp.*"/ -->	<!-- auto-import import-name="com.mycompany.myapp.ClassOne"/ --></esper-configuration>

=== intelie/esper/trunk/etc/regression/esper.test.readconfig.cfg.xml
<?xml version="1.0" encoding="UTF-8"?><esper-configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../esper-configuration-1-0.xsd">		<event-type alias="MySampleEventOne" class="com.mycompany.myapp.MySampleEventOne"/>	<event-type alias="MySampleEventTwo" class="com.mycompany.myapp.MySampleEventTwo"/>	<event-type alias="MyNoSchemaXMLEventAlias">		<xml-dom root-element-name="MyNoSchemaEvent" >			<xpath-property property-name="element1" xpath="/myevent/element1" type="number"/>		</xml-dom>	</event-type>		<event-type alias="MySchemaXMLEventAlias">		<xml-dom root-element-name="MySchemaEvent" root-element-namespace="samples:schemas:simpleSchema" schema-resource="MySchemaXMLEvent.xsd" 				default-namespace="default-name-space">			<namespace-prefix prefix="ss" namespace="samples:schemas:simpleSchema"/>			<xpath-property property-name="element1" xpath="/myevent/element1" type="number"/>		</xml-dom>	</event-type>		<event-type alias="MyMapEvent">		<java-util-map>		  	<map-property name="myInt" class="int"/>	  		<map-property name="myString" class="string"/>	  	</java-util-map>	</event-type>		<event-type alias="MyLegacyTypeEvent" class="com.mycompany.package.MyLegacyTypeEvent">		<legacy-type accessor-style="public" code-generation="enabled">			<method-property name="mymethodprop" accessor-method="myAccessorMethod" />			<field-property name="myfieldprop" accessor-field="myFieldName" />		</legacy-type>	</event-type>	<auto-import import-name="com.mycompany.myapp.*"/>	<auto-import import-name="com.mycompany.myapp.ClassOne"/>		<database-reference name="mydb1">		<connection-factory>			<initial-context-datasource context-lookup="java:comp/env/jdbc/mydb">				<env-property name="java.naming.factory.initial" value ="com.myclass.CtxFactory"/>				<env-property name="java.naming.provider.url" value ="iiop://localhost:1050"/>			</initial-context-datasource>		</connection-factory>		<policy schema="myschema1">			<connection-lifecycle value="new"/>		</policy>	</database-reference>		<database-reference name="mydb2">		<connection-factory>			<drivermanager class-name="my.sql.Driver" url="jdbc:mysql://localhost/test?user=root&amp;password=welcome" user="myuser" password="mypassword">				<connection-arg name="user" value ="myuser"/>				<connection-arg name="password" value ="mypassword"/>				<connection-arg name="somearg" value ="someargvalue"/>			</drivermanager>		</connection-factory>		<policy schema="myschema2">			<connection-lifecycle value="retain"/>		</policy>	</database-reference></esper-configuration>

=== intelie/esper/etc/esper.sample.cfg.xml
<?xml version="1.0" encoding="UTF-8"?><!-- 	Sample configuration file.--><esper-configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="esper-configuration-1-0.xsd">		<!-- Event type alias names for plain Java-object events -->		<event-type alias="MyJavaBeanEvent" class="com.mycompany.myapp.MySampleEvent"/>	<!-- Event type alias names for java.util.Map events -->		<event-type alias="MyMapEvent">		<java-util-map>			<map-property name="carId" class="int"/>			<map-property name="carName" class="string"/>			<map-property name="assembly" class="com.mycompany.Assembly"/>		</java-util-map>	</event-type>		<!-- Event type alias names for XML document object model DOM events of type org.w3c.dom.Node-->		<event-type alias="MyXMLNodeEvent">		<xml-dom root-element-name="rootelement" schema-resource="optional.xsd" default-namespace="urn:specification:xml:myschema:1">			<namespace-prefix prefix="myprefix" namespace="urn:specification:xml:myschema:1"/>			<xpath-property property-name="mycount" xpath="count(/myprefix:elementone/myprefix:elementtwo)" type="number"/>		</xml-dom>	</event-type>	<!-- Import Packages and Classes -->	<auto-import import-name="com.mycompany.mypackage.*"/>	<auto-import import-name="com.mycompany.myapp.MyUtilityClass"/>	</esper-configuration>

=== intelie/esper/trunk/etc/esper.yves.test.readconfig.cfg.xml
<?xml version="1.0" encoding="UTF-8"?><esper-configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../esper-configuration-1-0.xsd">		<!-- event-type alias="MySampleEventOne" class="net.esper.example.stockticker.eventbean.StockTick"/ -->	<!-- event-type alias="MySampleEventTwo" class="net.esper.example.stockticker.eventbean.StockTick"/ -->	<event-type alias="MyNoSchemaXMLEventAlias">		<xml-dom root-element-name="MyNoSchemaEvent" >			<xpath-property property-name="element1" xpath="/myevent/element1" type="number"/>		</xml-dom>	</event-type>		<event-type alias="MySchemaXMLEventAlias">		<xml-dom root-element-name="MySchemaEvent" root-element-namespace="samples:schemas:simpleSchema" xsi:schemaLocation="samples:schemas:simpleSchema simpleSchema.xsd" 				default-namespace="default-name-space">				<namespace-prefix prefix="ss" namespace="samples:schemas:simpleSchema"/>			<xpath-property property-name="element1" xpath="/myevent/element1" type="number"/>		</xml-dom>	</event-type>		<event-type alias="MyMapEvent">		<java-util-map>		  	<map-property name="myInt" class="java.lang.Integer"/>		  	<map-property name="myDouble" class="java.lang.Double"/>	  		<map-property name="myString" class="java.lang.String"/>		  	<!-- map-property name="myInt" class="int"/>	  		<map-property name="myString" class="string"/ -->	  			  	</java-util-map>	</event-type>	<ouput-adapter>		<adapter-loader class="net.esper.adapter.SpringContextLoader">			<!-- SpringApplicationContext translates into Spring 			     ClassPathXmlApplicationContext or FileSystemXmlApplicationContext etc...-->			<!-- Only one app-context of a sort could be used.			     When both attributes are used classpath and file, classpath prevails -->			<classpath-app-context name="spring\jms-spring.xml"/>			<file-app-context name="F:\Esper\jmsadapter\trunk\esperio\etc\spring\jms-spring.xml"/>		</adapter-loader>	</ouput-adapter>	<!-- auto-import import-name="com.mycompany.myapp.*"/ -->	<!-- auto-import import-name="com.mycompany.myapp.ClassOne"/ --></esper-configuration>
