=== intelie/esper/esper/etc/regression/sensorSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Observation">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ID" type="xs:string"/>
        <xs:element ref="Tag" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="Command" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="Sensor">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ID" type="xs:string"/>
        <xs:element ref="Observation" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Tag">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ID" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== intelie/esper/trunk/esper/etc/regression/sensor.xml
<?xml version="1.0" encoding="UTF-8"?>
<Sensor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sensorSchema.xsd">
	<ID>urn:epc:1:4.16.36</ID>
	<Observation Command="READ_PALLET_TAGS_ONLY">
		<ID>00000001</ID>
		<Tag>
			<ID>urn:epc:1:2.24.400</ID>
		</Tag>
		<Tag>
			<ID>urn:epc:1:2.24.401</ID>
		</Tag>
	</Observation>
</Sensor>
