=== intelie/esper/trunk/esperio/etc/esperio-opentickadapter-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.espertech.com/schema/esperio-opentick" elementFormDefault="qualified" xmlns:esper="http://www.espertech.com/schema/esperio-opentick" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="esper-opentickadapter-configuration">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="esper:connection" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="esper:streams" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="esper:symbollists" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="esper:stream-symbollists" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="connection">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="esper:hosts" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="esper:login" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="hosts">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="esper:host" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="host">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="port" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="login">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="password" type="xs:string" use="required"/>
			<xs:attribute name="timeout-msec" type="xs:long" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="streams">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="esper:stream" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="stream">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="enable" type="xs:boolean" use="required"/>
			<xs:attribute name="engine-uri" type="xs:string" use="required"/>
			<xs:attribute name="type-name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="symbollists">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="esper:symbollist" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="symbollist">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="exchange" type="xs:string" use="required"/>
			<xs:attribute name="symbols" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="stream-symbollists">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="esper:stream-symbollist" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="stream-symbollist">
		<xs:complexType>
			<xs:attribute name="stream" type="xs:string" use="required"/>
			<xs:attribute name="symbollist" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== intelie/esper/esperio/etc/esperio-opentickadapter-config-sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<esper-opentickadapter-configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://www.espertech.com/schema/esperio-opentick"
    xsi:noNamespaceSchemaLocation="esperio-opentickadapter-config.xsd">
    
	 <!-- Connection-level information goes here. -->
	<connection>
	    <hosts>
			<host name="feed1.opentick.com" port="10010"/>
			<host name="feed2.opentick.com" port="10010"/>
	    </hosts>
	    <login name="login" password="password" timeout-msec="20000"/>	    
	</connection>
    <!-- 
		List of streams and engine instance destination; The stream name is a reference to the event subscribed to. 
		Only the following 4 stream names are recognized:  OTQuote, OTMMQuote, OTTrade, OTBBO.
		Each stream translates into a "addRtQuoteListener" or equivalent listener on the OT client.
	-->
	<streams>
		<stream name="OTQuote" enable="true" engine-uri="MyEngineURI" type-name="OTQuote"/>
		<stream name="OTMMQuote" enable="true" engine-uri="MyEngineURI" type-name="OTMMQuote"/>
		<stream name="OTTrade" enable="true" engine-uri="MyEngineURI" type-name="OTTrade"/>
		<stream name="OTBBO" enable="true" engine-uri="MyEngineURI" type-name="OTBBO"/>
	</streams>
	<!-- List of symbols: Each provides a combination of exchange and symbols. -->
	<symbollists>
		<!-- Exchange and comma-separated list of symbols. -->
		<symbollist name="list1" exchange="NASDAQ" symbols="MSFT,VDNX"/>
	</symbollists>
	<!-- 
		Association of streams to symbols, multiple associations are allowed however a subscription is once per symbol.. 
		Each exchange+symbol is subscribed to via requestTickStream on the OT client, for the mask indicated via stream.		
	-->
	<stream-symbollists>
		<stream-symbollist stream="OTQuote" symbollist="list1"/>
		<stream-symbollist stream="OTMMQuote" symbollist="list1"/>
		<stream-symbollist stream="OTTrade" symbollist="list1"/>
		<stream-symbollist stream="OTBBO" symbollist="list1"/>
	</stream-symbollists>
</esper-opentickadapter-configuration>
